-- Cocoa Field Station shared Supabase/PostgreSQL schema.
-- Run once in the Supabase Dashboard SQL Editor as the project owner.
-- Application servers connect with private credentials; browser/mobile roles
-- are intentionally denied direct table access (RLS enabled, no client policies).

CREATE TABLE IF NOT EXISTS public.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    email VARCHAR(254) NOT NULL UNIQUE,
    password_hash VARCHAR(512) NOT NULL,
    role VARCHAR(20) NOT NULL DEFAULT 'inputer'
        CHECK (role IN ('inputer', 'admin', 'administrator', 'manager')),
    is_active SMALLINT NOT NULL DEFAULT 1 CHECK (is_active IN (0, 1)),
    google_sub VARCHAR(255) UNIQUE,
    totp_secret_enc TEXT,
    totp_enabled SMALLINT NOT NULL DEFAULT 0 CHECK (totp_enabled IN (0, 1)),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public.login_challenges (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    code_hash CHAR(64) NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    attempts SMALLINT NOT NULL DEFAULT 0 CHECK (attempts BETWEEN 0 AND 255),
    consumed_at TIMESTAMPTZ,
    purpose VARCHAR(20) NOT NULL DEFAULT 'totp_login'
        CHECK (purpose IN ('totp_setup', 'totp_login')),
    pending_totp_secret_enc TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_challenge_user ON public.login_challenges(user_id, created_at);

CREATE TABLE IF NOT EXISTS public.api_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    token_hash CHAR(64) NOT NULL UNIQUE,
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_token_user ON public.api_tokens(user_id);

-- Streamlit Google OIDC identities remain separate from Expo password accounts.
CREATE TABLE IF NOT EXISTS public.auth_accounts (
    google_sub VARCHAR(255) PRIMARY KEY,
    email VARCHAR(254) NOT NULL,
    name VARCHAR(120) NOT NULL,
    role VARCHAR(20) NOT NULL DEFAULT 'inputer'
        CHECK (role IN ('inputer', 'admin', 'administrator', 'manager')),
    totp_secret_enc TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_auth_accounts_email ON public.auth_accounts(LOWER(email));

CREATE TABLE IF NOT EXISTS public.blocked_auth_identities (
    google_sub VARCHAR(255) PRIMARY KEY,
    email VARCHAR(254) NOT NULL,
    blocked_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Shared invitation list: invited_by stores either an Expo user ID or a
-- Streamlit email, depending on which app created the invitation.
CREATE TABLE IF NOT EXISTS public.inputer_invites (
    email VARCHAR(254) PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    invited_by VARCHAR(254) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public.field_plots (
    plot_id VARCHAR(40) PRIMARY KEY,
    description VARCHAR(200) NOT NULL
);

-- Weather observations are shared by the web and mobile apps.
CREATE TABLE IF NOT EXISTS public.field_weather (
    plot_id VARCHAR(40) NOT NULL REFERENCES public.field_plots(plot_id) ON DELETE CASCADE,
    observation_date DATE NOT NULL,
    rainfall_mm NUMERIC(7,2) NOT NULL CHECK (rainfall_mm >= 0),
    humidity_pct NUMERIC(5,2) NOT NULL CHECK (humidity_pct BETWEEN 0 AND 100),
    temp_c NUMERIC(5,2) NOT NULL,
    days_since_last_spray INTEGER NOT NULL CHECK (days_since_last_spray >= 0),
    inspection_note VARCHAR(500),
    entered_by BIGINT REFERENCES public.users(id) ON DELETE SET NULL,
    entered_by_email VARCHAR(254),
    PRIMARY KEY (plot_id, observation_date)
);

-- Recommendation and human-review records are also shared. user_id is NULL
-- for Streamlit records, which identify the actor by entered_by_email.
CREATE TABLE IF NOT EXISTS public.field_decisions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES public.users(id) ON DELETE SET NULL,
    entered_by_email VARCHAR(254),
    plot_id VARCHAR(40) NOT NULL REFERENCES public.field_plots(plot_id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    risk_bucket VARCHAR(10) NOT NULL CHECK (risk_bucket IN ('low', 'medium', 'high')),
    recommendation VARCHAR(10) NOT NULL CHECK (recommendation IN ('spray', 'wait', 'inspect')),
    rationale TEXT NOT NULL,
    evidence_json JSONB NOT NULL DEFAULT '[]'::jsonb,
    confidence NUMERIC(4,3) NOT NULL CHECK (confidence BETWEEN 0 AND 1),
    gated SMALLINT NOT NULL DEFAULT 0 CHECK (gated IN (0, 1)),
    human_decision VARCHAR(10) CHECK (human_decision IN ('spray', 'wait', 'inspect')),
    human_reason VARCHAR(1000),
    cited_case_ids JSONB NOT NULL DEFAULT '[]'::jsonb
);
CREATE INDEX IF NOT EXISTS idx_field_decision_plot_date ON public.field_decisions(plot_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_field_decision_user_date ON public.field_decisions(user_id, created_at DESC);

INSERT INTO public.field_plots(plot_id, description) VALUES
    ('Plot A', 'Rising rain and humidity'),
    ('Plot B', 'Recent gaps in observations'),
    ('Plot C', 'Middle-range conditions')
ON CONFLICT (plot_id) DO NOTHING;

-- Supabase's Data API roles cannot read or change these tables. The app
-- backends use their private server-side database connection and enforce roles.
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.login_challenges ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.api_tokens ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.auth_accounts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.blocked_auth_identities ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inputer_invites ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.field_plots ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.field_weather ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.field_decisions ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.users, public.login_challenges, public.api_tokens,
    public.auth_accounts, public.blocked_auth_identities, public.inputer_invites,
    public.field_plots, public.field_weather, public.field_decisions
    FROM anon, authenticated;
