[theme]
base = "light"
primaryColor = "#365A43"
backgroundColor = "#F7F5EF"
secondaryBackgroundColor = "#EDEBE3"
textColor = "#24372D"
font = "sans-serif"
headingFont = "serif"
codeFont = "monospace"
borderColor = "#DAD8CE"
